swagger: '2.0'
info:
  version: 1.0.0
  title: Location Images API
  description: staging https://4ydzm9qes6.execute-api.eu-north-1.amazonaws.com/staging <br> production https://vp694vsg72.execute-api.eu-north-1.amazonaws.com/production
schemes:
- https
paths:
 /location/{locationId}:
    get:
      summary: Get location images
      description: Example URL /location/60477c10093d2f0008cdf0ce
      produces:
      - application/json
      parameters:
      - in: header
        name: Authorization
        description: Header format 'basic Base64("username:password")'
        type: string
        required: true

      - in: path
        name: locationId
        type: string
        required: true

      responses:
        401:
          description: Unauthorized OR InvalidAuthorizationToken
        404:
          description: InvalidLocation
        200:
          description: 'Returns the individual locker images at a location'
          examples: 
            application/json: {
  "A": [
    {
      "expiresAt": "2023-12-18T12:00:07Z",
      "prio": 0,
      "url": "https://uploaded-location-images.s3.eu-north-1.amazonaws.com/production/Axel/2021-11-16/ebaaf97f-c7cf-46f7-8e4d-7a79fd18cfb5.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIAQJS2D7QFM7WLOAPK%2F20231211%2Feu-north-1%2Fs3%2Faws4_request&X-Amz-Date=20231211T120007Z&X-Amz-Expires=604800&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEJz%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCmV1LW5vcnRoLTEiSDBGAiEAo9mRQ%2Boqj4ui%2F1%2BewoWsSNGzVvx1H4SBI5U0CIjtco4CIQDm3ddD6ykR9UaNxTUt0tJEQi4qv499Y5n4Fds8XOW%2FkiqQAwgVEAIaDDAyMDU5MDA5OTQ2NiIMDLC8Ay7iwR9usoIBKu0Cg5ExL8WIBgk6jvcpyJUG036KFUJVlW68c5hq1%2FaLgyh%2FPRtZ6co%2BwNiI5t4RD%2BQfyL9XVwHQzamJ%2B4eA%2BUZndy2ODMKlpnlCnzFj3m2ie0GHOboppFB%2BKubqmy%2FVn0Hg4m7E0Nn24bEJ5fafRYu02nNhGm%2Bbo7PQ%2FKyHs1oT00iTaBIut%2FGl1OQ71vCKYKNcW6yOHGMScKdmmPrLUHjC550Yc2peQ%2FJeCvMmwzE5jA1LBUZAEF39aRf3oiX9fcfsh6IYx1QUZ160XtzKPpyd69cJ%2BuZ65Y23eVCuxGnhFqOKZGGrCHEbZtVrP6QJkN1VpcouPxVJYP2Bg1ZcyZqzbNxeS7j263IXvimNjLU%2ByGcjk4KlJjowBTKNwolCnp0Z91Bajp9Y3TORZHJsww8g%2Fdn6qGhsVeI4OwSNmxUO3izRhNSQwKYnDc00bwPAIy8J9cPS8Lmr8hPB8ma3qclDRRm3vvJytMB35uS4mq8w4vLbqwY6nAGZOaTYyD9%2F4uZWxH34EGPAm%2Fw6TgVEUZz01vBtN%2B2a7W8qN%2BWgXmajhjRZ%2F8XfOB4bJ4TJdXKpfh2p%2BoJA3SvMAiUfoCMxc5lXgNRCUogfi3pKR%2BiNhY4mA%2FH7Xt8lh9UlaTCYoKPELd5JJ75gWeWTHwsLLXhHMeoYZNIZCDh%2BuZ%2FBMgSXRPB%2FL6NKEgJEBs57ECtSjlA21o4GSr0%3D&X-Amz-SignedHeaders=host&X-Amz-Signature=0397a212b6024a7d2fe6cb0fe237e7017aa02e1981fa70b7aaaf37fb123fbbd1"
    },
    {
      "expiresAt": "2023-12-18T12:00:07Z",
      "prio": 1,
      "url": "https://uploaded-location-images.s3.eu-north-1.amazonaws.com/production/Axel/2021-11-16/5c94a13c-df8b-4c64-b866-a0e3687d893e.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIAQJS2D7QFM7WLOAPK%2F20231211%2Feu-north-1%2Fs3%2Faws4_request&X-Amz-Date=20231211T120007Z&X-Amz-Expires=604800&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEJz%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCmV1LW5vcnRoLTEiSDBGAiEAo9mRQ%2Boqj4ui%2F1%2BewoWsSNGzVvx1H4SBI5U0CIjtco4CIQDm3ddD6ykR9UaNxTUt0tJEQi4qv499Y5n4Fds8XOW%2FkiqQAwgVEAIaDDAyMDU5MDA5OTQ2NiIMDLC8Ay7iwR9usoIBKu0Cg5ExL8WIBgk6jvcpyJUG036KFUJVlW68c5hq1%2FaLgyh%2FPRtZ6co%2BwNiI5t4RD%2BQfyL9XVwHQzamJ%2B4eA%2BUZndy2ODMKlpnlCnzFj3m2ie0GHOboppFB%2BKubqmy%2FVn0Hg4m7E0Nn24bEJ5fafRYu02nNhGm%2Bbo7PQ%2FKyHs1oT00iTaBIut%2FGl1OQ71vCKYKNcW6yOHGMScKdmmPrLUHjC550Yc2peQ%2FJeCvMmwzE5jA1LBUZAEF39aRf3oiX9fcfsh6IYx1QUZ160XtzKPpyd69cJ%2BuZ65Y23eVCuxGnhFqOKZGGrCHEbZtVrP6QJkN1VpcouPxVJYP2Bg1ZcyZqzbNxeS7j263IXvimNjLU%2ByGcjk4KlJjowBTKNwolCnp0Z91Bajp9Y3TORZHJsww8g%2Fdn6qGhsVeI4OwSNmxUO3izRhNSQwKYnDc00bwPAIy8J9cPS8Lmr8hPB8ma3qclDRRm3vvJytMB35uS4mq8w4vLbqwY6nAGZOaTYyD9%2F4uZWxH34EGPAm%2Fw6TgVEUZz01vBtN%2B2a7W8qN%2BWgXmajhjRZ%2F8XfOB4bJ4TJdXKpfh2p%2BoJA3SvMAiUfoCMxc5lXgNRCUogfi3pKR%2BiNhY4mA%2FH7Xt8lh9UlaTCYoKPELd5JJ75gWeWTHwsLLXhHMeoYZNIZCDh%2BuZ%2FBMgSXRPB%2FL6NKEgJEBs57ECtSjlA21o4GSr0%3D&X-Amz-SignedHeaders=host&X-Amz-Signature=ae1daf85704ac3192283f191546cf489e43bc2a089e50a6c882948801a2cb97e"
    }
  ],
  "B": []
}