info:
  title: iBoxen WebLockerAPI
  description: Restful endpoints for integrating iBoxen WebLocker
  version: 1.0.0
paths:
  /v1/user/missions:
    get:
      summary: getMissions(locationId | coordinates, user?) 
      parameters:
        - name: locationId
          in: query
          type: string
          required: true
          description: Location ID registered with iBoxen
        - name: coordinates
          in: query
          type: string
          required: true
          description: Latitude,Longitude
        - name: user
          in: query
          type: string
          # required: true
          description: User ID
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  parcels:
                    type: array
                    items:
                      type: object
                      properties:
                        parcelId:
                          type: string
                        status:
                          type: string
                        boxId:
                          type: string
                        locker:
                          type: string
                  pickups:
                    type: array
                    items:
                      type: object
                      properties:
                        parcelId:
                          type: string
                        status:
                          type: string
                        boxId:
                          type: string
                        locker:
                          type: string
              example:
                parcels:
                  - parcelId: string
                    status: string
                    boxId: string
                    locker: string
                pickups:
                  - parcelId: string
                    status: string
                    boxId: string
                    locker: string
        "503":
          description: Device offline
      tags:
        - Driver / Consumer -endpoints
      security:
        - ApiKeyAuth: []
  /v1/user/parcel:
    get:
      summary: getParcel(parcelId, locationId | coordinates, user?)
      parameters:
        - name: parcelId
          in: query
          type: string
          required: true
          description: Parcel ID registered with iBoxen
        - name: coordinates
          in: query
          type: string
          required: true
          description: Latitude,Longitude
        - name: user
          in: query
          type: string
          # required: true
          description: User ID
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  parcelId:
                    type: string
                  status:
                    type: string
                  boxId:
                    type: string
                  locker:
                    type: string
              example:
                - parcelId: string
                  status: string
                  boxId: string
                  locker: string
        "503":
          description: Device offline
      tags:
        - Driver / Consumer -endpoints
      security:
        - ApiKeyAuth: []

  /v1/user/compartment/sense:
    get:
      summary: senseParcelCompartment(parcelId, locationId | coordinates, user?)
      parameters:
        - name: body
          in: body
          description: request body
          required: true
          schema:
            type: object
            properties:
              parcelId:
                type: string
                description: Parcel ID registered with iBoxen
              user:
                type: string
                description: User ID (optional)
              locationId:
                type: string
                description: Location ID (optional)
              coordinates:
                type: string
                description: Latitude,Longitude (optional)
      tags:
        - Driver / Consumer -endpoints


  /v1/user/compartment/open:
    post:
      summary: openParcelCompartment(parcelId, locationId | coordinates, user?)
      parameters:
        - name: body
          in: body
          description: request body
          required: true
          schema:
            type: object
            properties:
              parcelId:
                type: string
                description: Parcel ID registered with iBoxen
              user:
                type: string
                description: User ID (optional)
              locationId:
                type: string
                description: Location ID (optional)
              coordinates:
                type: string
                description: Latitude,Longitude (optional)
      tags:
        - Driver / Consumer -endpoints

  /v1/user/parcel/status:
    post:
      summary: setParcelStatus(parcelId, status, user?)
      parameters:
        - name: body
          in: body
          description: request body
          required: true
          schema:
            type: object
            properties:
              parcelId:
                type: string
                description: Parcel ID registered with iBoxen
              status:
                type: string
                description: Status of the parcel (e.g., "delivered", "picked up")
              user:
                type: string
                description: User ID (optional)
      tags:
        - Driver / Consumer -endpoints

  /v1/user/compartment/change:
    post:
      summary: changeCompartment(parcelId, size?; larger | smaller | same, user?)
      parameters:
        - name: body
          in: body
          description: request body
          required: true
          schema:
            type: object
            properties:
              parcelId:
                type: string
                description: Parcel ID registered with iBoxen
              size:
                type: string
                description: Size of the compartment (e.g., "larger", "smaller", "same")
              user:
                type: string
                description: User ID (optional)
      tags:
        - Driver / Consumer -endpoints


  /v1/user/report-hardware:
    post:
      summary: raportHardware(parcelId, status, user?)
      parameters:
        - name: body
          in: body
          description: request body
          required: true
          schema:
            type: object
            properties:
              parcelId:
                type: string
                description: Parcel ID registered with iBoxen
              status:
                type: string
                description: Status of the parcel (e.g., "delivered", "picked up")
              user:
                type: string
                description: User ID (optional)
      tags:
        - Driver / Consumer -endpoints
  /v1/user/report-allocation:
    post:
      summary: reportAllocation(parcelId, status, user?)
      parameters:
        - name: body
          in: body
          description: request body
          required: true
          schema:
            type: object
            properties:
              parcelId:
                type: string
                description: Parcel ID registered with iBoxen
              status:
                type: string
                description: Status of the parcel (e.g., "delivered", "picked up")
              user:
                type: string
                description: User ID (optional)
      tags:
        - Driver / Consumer -endpoints


  /v1/user/location/report:
    post:
      summary: reportLocation(locationId | coordinates, report, user?) 
      parameters:
        - name: body
          in: body
          description: request body
          required: true
          schema:
            type: object
            properties:
              locationId:
                type: string
                description: Location ID registered with iBoxen
              report:
                type: string
                description: Report of the location (e.g., "damaged", "missing")
              user:
                type: string
                description: User ID (optional)
      tags:
        - Driver / Consumer -endpoints

  /v1/user/latest-parcel:
    get:
      summary: getLatestParcel(locationId | coordinates, user?)
      parameters:
        - name: locationId
          in: query
          type: string
          required: true
          description: Location ID registered with iBoxen
        - name: coordinates
          in: query
          type: string
          required: true
          description: Latitude,Longitude
        - name: user
          in: query
          type: string
          # required: true
          description: User ID
      responses:
        "200":
          content:
            application/json:
              example:
                - isOpen: true
                - isOpen: false
        "503":
          description: Device offline
      tags:
        - Driver -endpoints
  /health:
    get:
      summary: Health check for this API
      description: ""
      parameters: []
      responses:
        "200":
          content:
            application/json:
              example:
                status: healthy
      tags:
        - Health
      security:
        - ApiKeyAuth: []
responses: {}
definitions: {}
tags: []
swagger: null
securityDefinitions:
  ApiKeyAuth:
    type: apiKey
    in: header
    name: Authorization
openapi: 3.0.1
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
